/**
 * This class is generated by jOOQ
 */
package jdblender.jooq.db.public_.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jdblender.jooq.db.public_.Keys;
import jdblender.jooq.db.public_.Public;
import jdblender.jooq.db.public_.tables.records.SeriesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Series extends TableImpl<SeriesRecord> {

    private static final long serialVersionUID = 1942462044;

    /**
     * The reference instance of <code>PUBLIC.SERIES</code>
     */
    public static final Series SERIES = new Series();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeriesRecord> getRecordType() {
        return SeriesRecord.class;
    }

    /**
     * The column <code>PUBLIC.SERIES.ID</code>.
     */
    public final TableField<SeriesRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.SERIES.BRAND_ID</code>.
     */
    public final TableField<SeriesRecord, Long> BRAND_ID = createField("BRAND_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.SERIES.NAME</code>.
     */
    public final TableField<SeriesRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

    /**
     * Create a <code>PUBLIC.SERIES</code> table reference
     */
    public Series() {
        this("SERIES", null);
    }

    /**
     * Create an aliased <code>PUBLIC.SERIES</code> table reference
     */
    public Series(String alias) {
        this(alias, SERIES);
    }

    private Series(String alias, Table<SeriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Series(String alias, Table<SeriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SeriesRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SeriesRecord>> getKeys() {
        return Arrays.<UniqueKey<SeriesRecord>>asList(Keys.CONSTRAINT_9);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SeriesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SeriesRecord, ?>>asList(Keys.CONSTRAINT_91);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Series as(String alias) {
        return new Series(alias, this);
    }

    /**
     * Rename this table
     */
    public Series rename(String name) {
        return new Series(name, null);
    }
}
