/**
 * This class is generated by jOOQ
 */
package jdblender.jooq.db.public_.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jdblender.jooq.db.public_.Keys;
import jdblender.jooq.db.public_.Public;
import jdblender.jooq.db.public_.tables.records.SpareToModelRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpareToModel extends TableImpl<SpareToModelRecord> {

    private static final long serialVersionUID = -2115561712;

    /**
     * The reference instance of <code>PUBLIC.SPARE_TO_MODEL</code>
     */
    public static final SpareToModel SPARE_TO_MODEL = new SpareToModel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpareToModelRecord> getRecordType() {
        return SpareToModelRecord.class;
    }

    /**
     * The column <code>PUBLIC.SPARE_TO_MODEL.SPARE_ID</code>.
     */
    public final TableField<SpareToModelRecord, Long> SPARE_ID = createField("SPARE_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.SPARE_TO_MODEL.MODEL_ID</code>.
     */
    public final TableField<SpareToModelRecord, Long> MODEL_ID = createField("MODEL_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.SPARE_TO_MODEL</code> table reference
     */
    public SpareToModel() {
        this("SPARE_TO_MODEL", null);
    }

    /**
     * Create an aliased <code>PUBLIC.SPARE_TO_MODEL</code> table reference
     */
    public SpareToModel(String alias) {
        this(alias, SPARE_TO_MODEL);
    }

    private SpareToModel(String alias, Table<SpareToModelRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpareToModel(String alias, Table<SpareToModelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SpareToModelRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SpareToModelRecord, ?>>asList(Keys.CONSTRAINT_5, Keys.CONSTRAINT_55);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpareToModel as(String alias) {
        return new SpareToModel(alias, this);
    }

    /**
     * Rename this table
     */
    public SpareToModel rename(String name) {
        return new SpareToModel(name, null);
    }
}
