/**
 * This class is generated by jOOQ
 */
package jdblender.jooq.db.public_.tables.records;


import javax.annotation.Generated;

import jdblender.jooq.db.public_.tables.Models;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelsRecord extends UpdatableRecordImpl<ModelsRecord> implements Record3<Long, Long, String> {

    private static final long serialVersionUID = -1843590720;

    /**
     * Setter for <code>PUBLIC.MODELS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.MODELS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.MODELS.SERIES_ID</code>.
     */
    public void setSeriesId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.MODELS.SERIES_ID</code>.
     */
    public Long getSeriesId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.MODELS.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.MODELS.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Models.MODELS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Models.MODELS.SERIES_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Models.MODELS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSeriesId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelsRecord value2(Long value) {
        setSeriesId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelsRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelsRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelsRecord
     */
    public ModelsRecord() {
        super(Models.MODELS);
    }

    /**
     * Create a detached, initialised ModelsRecord
     */
    public ModelsRecord(Long id, Long seriesId, String name) {
        super(Models.MODELS);

        set(0, id);
        set(1, seriesId);
        set(2, name);
    }
}
