/**
 * This class is generated by jOOQ
 */
package jdblender.jooq.db.public_.tables.records;


import javax.annotation.Generated;

import jdblender.jooq.db.public_.tables.SpareToModel;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpareToModelRecord extends TableRecordImpl<SpareToModelRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 214206913;

    /**
     * Setter for <code>PUBLIC.SPARE_TO_MODEL.SPARE_ID</code>.
     */
    public void setSpareId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.SPARE_TO_MODEL.SPARE_ID</code>.
     */
    public Long getSpareId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.SPARE_TO_MODEL.MODEL_ID</code>.
     */
    public void setModelId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.SPARE_TO_MODEL.MODEL_ID</code>.
     */
    public Long getModelId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SpareToModel.SPARE_TO_MODEL.SPARE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SpareToModel.SPARE_TO_MODEL.MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getSpareId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpareToModelRecord value1(Long value) {
        setSpareId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpareToModelRecord value2(Long value) {
        setModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpareToModelRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpareToModelRecord
     */
    public SpareToModelRecord() {
        super(SpareToModel.SPARE_TO_MODEL);
    }

    /**
     * Create a detached, initialised SpareToModelRecord
     */
    public SpareToModelRecord(Long spareId, Long modelId) {
        super(SpareToModel.SPARE_TO_MODEL);

        set(0, spareId);
        set(1, modelId);
    }
}
