package jdblender.cayenne.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _SpareToModel was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpareToModel extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String MODEL_ID_PK_COLUMN = "MODEL_ID";

    public static final Property<Long> MODEL_ID = new Property<Long>("modelId");
    public static final Property<Long> SPARE_ID = new Property<Long>("spareId");

    public void setModelId(Long modelId) {
        writeProperty("modelId", modelId);
    }
    public Long getModelId() {
        return (Long)readProperty("modelId");
    }

    public void setSpareId(Long spareId) {
        writeProperty("spareId", spareId);
    }
    public Long getSpareId() {
        return (Long)readProperty("spareId");
    }

}
