package jdblender.cayenne.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import jdblender.cayenne.model.Brands;
import jdblender.cayenne.model.Models;

/**
 * Class _Spares was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Spares extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Long> BRAND_ID = new Property<Long>("brandId");
    public static final Property<Boolean> FLAG = new Property<Boolean>("flag");
    public static final Property<Long> ID = new Property<Long>("id");
    public static final Property<String> LABEL = new Property<String>("label");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<Integer> NUM = new Property<Integer>("num");
    public static final Property<Brands> BRAND = new Property<Brands>("brand");
    public static final Property<List<Models>> MODELS = new Property<List<Models>>("models");

    public void setBrandId(long brandId) {
        writeProperty("brandId", brandId);
    }
    public long getBrandId() {
        Object value = readProperty("brandId");
        return (value != null) ? (Long) value : 0;
    }

    public void setFlag(boolean flag) {
        writeProperty("flag", flag);
    }
	public boolean isFlag() {
        Boolean value = (Boolean)readProperty("flag");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setId(long id) {
        writeProperty("id", id);
    }
    public long getId() {
        Object value = readProperty("id");
        return (value != null) ? (Long) value : 0;
    }

    public void setLabel(String label) {
        writeProperty("label", label);
    }
    public String getLabel() {
        return (String)readProperty("label");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setNum(int num) {
        writeProperty("num", num);
    }
    public int getNum() {
        Object value = readProperty("num");
        return (value != null) ? (Integer) value : 0;
    }

    public void setBrand(Brands brand) {
        setToOneTarget("brand", brand, true);
    }

    public Brands getBrand() {
        return (Brands)readProperty("brand");
    }


    public void addToModels(Models obj) {
        addToManyTarget("models", obj, true);
    }
    public void removeFromModels(Models obj) {
        removeToManyTarget("models", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Models> getModels() {
        return (List<Models>)readProperty("models");
    }


}
