package jdblender.cayenne.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import jdblender.cayenne.model.Models;
import jdblender.cayenne.model.Spares;

/**
 * Class _SpareToModel was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpareToModel extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String MODEL_ID_PK_COLUMN = "MODEL_ID";
    public static final String SPARE_ID_PK_COLUMN = "SPARE_ID";

    public static final Property<Long> MODEL_ID = new Property<Long>("modelId");
    public static final Property<Long> SPARE_ID = new Property<Long>("spareId");
    public static final Property<Models> MODEL = new Property<Models>("model");
    public static final Property<Spares> SPARE = new Property<Spares>("spare");

    public void setModelId(long modelId) {
        writeProperty("modelId", modelId);
    }
    public long getModelId() {
        Object value = readProperty("modelId");
        return (value != null) ? (Long) value : 0;
    }

    public void setSpareId(long spareId) {
        writeProperty("spareId", spareId);
    }
    public long getSpareId() {
        Object value = readProperty("spareId");
        return (value != null) ? (Long) value : 0;
    }

    public void setModel(Models model) {
        setToOneTarget("model", model, true);
    }

    public Models getModel() {
        return (Models)readProperty("model");
    }


    public void setSpare(Spares spare) {
        setToOneTarget("spare", spare, true);
    }

    public Spares getSpare() {
        return (Spares)readProperty("spare");
    }


}
