/**
 * This class is generated by jOOQ
 */
package jdblender.jooq.db.information_schema;


import javax.annotation.Generated;

import jdblender.jooq.db.information_schema.tables.Catalogs;
import jdblender.jooq.db.information_schema.tables.Collations;
import jdblender.jooq.db.information_schema.tables.ColumnPrivileges;
import jdblender.jooq.db.information_schema.tables.Columns;
import jdblender.jooq.db.information_schema.tables.Constants;
import jdblender.jooq.db.information_schema.tables.Constraints;
import jdblender.jooq.db.information_schema.tables.CrossReferences;
import jdblender.jooq.db.information_schema.tables.Domains;
import jdblender.jooq.db.information_schema.tables.FunctionAliases;
import jdblender.jooq.db.information_schema.tables.FunctionColumns;
import jdblender.jooq.db.information_schema.tables.Help;
import jdblender.jooq.db.information_schema.tables.InDoubt;
import jdblender.jooq.db.information_schema.tables.Indexes;
import jdblender.jooq.db.information_schema.tables.Locks;
import jdblender.jooq.db.information_schema.tables.QueryStatistics;
import jdblender.jooq.db.information_schema.tables.Rights;
import jdblender.jooq.db.information_schema.tables.Roles;
import jdblender.jooq.db.information_schema.tables.Schemata;
import jdblender.jooq.db.information_schema.tables.Sequences;
import jdblender.jooq.db.information_schema.tables.SessionState;
import jdblender.jooq.db.information_schema.tables.Sessions;
import jdblender.jooq.db.information_schema.tables.Settings;
import jdblender.jooq.db.information_schema.tables.TablePrivileges;
import jdblender.jooq.db.information_schema.tables.TableTypes;
import jdblender.jooq.db.information_schema.tables.Triggers;
import jdblender.jooq.db.information_schema.tables.TypeInfo;
import jdblender.jooq.db.information_schema.tables.Users;
import jdblender.jooq.db.information_schema.tables.Views;


/**
 * Convenience access to all tables in INFORMATION_SCHEMA
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>INFORMATION_SCHEMA.QUERY_STATISTICS</code>.
     */
    public static final QueryStatistics QUERY_STATISTICS = jdblender.jooq.db.information_schema.tables.QueryStatistics.QUERY_STATISTICS;

    /**
     * The table <code>INFORMATION_SCHEMA.SESSION_STATE</code>.
     */
    public static final SessionState SESSION_STATE = jdblender.jooq.db.information_schema.tables.SessionState.SESSION_STATE;

    /**
     * The table <code>INFORMATION_SCHEMA.LOCKS</code>.
     */
    public static final Locks LOCKS = jdblender.jooq.db.information_schema.tables.Locks.LOCKS;

    /**
     * The table <code>INFORMATION_SCHEMA.SESSIONS</code>.
     */
    public static final Sessions SESSIONS = jdblender.jooq.db.information_schema.tables.Sessions.SESSIONS;

    /**
     * The table <code>INFORMATION_SCHEMA.TRIGGERS</code>.
     */
    public static final Triggers TRIGGERS = jdblender.jooq.db.information_schema.tables.Triggers.TRIGGERS;

    /**
     * The table <code>INFORMATION_SCHEMA.DOMAINS</code>.
     */
    public static final Domains DOMAINS = jdblender.jooq.db.information_schema.tables.Domains.DOMAINS;

    /**
     * The table <code>INFORMATION_SCHEMA.CONSTANTS</code>.
     */
    public static final Constants CONSTANTS = jdblender.jooq.db.information_schema.tables.Constants.CONSTANTS;

    /**
     * The table <code>INFORMATION_SCHEMA.FUNCTION_COLUMNS</code>.
     */
    public static final FunctionColumns FUNCTION_COLUMNS = jdblender.jooq.db.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS;

    /**
     * The table <code>INFORMATION_SCHEMA.CONSTRAINTS</code>.
     */
    public static final Constraints CONSTRAINTS = jdblender.jooq.db.information_schema.tables.Constraints.CONSTRAINTS;

    /**
     * The table <code>INFORMATION_SCHEMA.CROSS_REFERENCES</code>.
     */
    public static final CrossReferences CROSS_REFERENCES = jdblender.jooq.db.information_schema.tables.CrossReferences.CROSS_REFERENCES;

    /**
     * The table <code>INFORMATION_SCHEMA.IN_DOUBT</code>.
     */
    public static final InDoubt IN_DOUBT = jdblender.jooq.db.information_schema.tables.InDoubt.IN_DOUBT;

    /**
     * The table <code>INFORMATION_SCHEMA.VIEWS</code>.
     */
    public static final Views VIEWS = jdblender.jooq.db.information_schema.tables.Views.VIEWS;

    /**
     * The table <code>INFORMATION_SCHEMA.COLLATIONS</code>.
     */
    public static final Collations COLLATIONS = jdblender.jooq.db.information_schema.tables.Collations.COLLATIONS;

    /**
     * The table <code>INFORMATION_SCHEMA.COLUMN_PRIVILEGES</code>.
     */
    public static final ColumnPrivileges COLUMN_PRIVILEGES = jdblender.jooq.db.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLE_PRIVILEGES</code>.
     */
    public static final TablePrivileges TABLE_PRIVILEGES = jdblender.jooq.db.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

    /**
     * The table <code>INFORMATION_SCHEMA.SCHEMATA</code>.
     */
    public static final Schemata SCHEMATA = jdblender.jooq.db.information_schema.tables.Schemata.SCHEMATA;

    /**
     * The table <code>INFORMATION_SCHEMA.FUNCTION_ALIASES</code>.
     */
    public static final FunctionAliases FUNCTION_ALIASES = jdblender.jooq.db.information_schema.tables.FunctionAliases.FUNCTION_ALIASES;

    /**
     * The table <code>INFORMATION_SCHEMA.RIGHTS</code>.
     */
    public static final Rights RIGHTS = jdblender.jooq.db.information_schema.tables.Rights.RIGHTS;

    /**
     * The table <code>INFORMATION_SCHEMA.ROLES</code>.
     */
    public static final Roles ROLES = jdblender.jooq.db.information_schema.tables.Roles.ROLES;

    /**
     * The table <code>INFORMATION_SCHEMA.USERS</code>.
     */
    public static final Users USERS = jdblender.jooq.db.information_schema.tables.Users.USERS;

    /**
     * The table <code>INFORMATION_SCHEMA.SEQUENCES</code>.
     */
    public static final Sequences SEQUENCES = jdblender.jooq.db.information_schema.tables.Sequences.SEQUENCES;

    /**
     * The table <code>INFORMATION_SCHEMA.HELP</code>.
     */
    public static final Help HELP = jdblender.jooq.db.information_schema.tables.Help.HELP;

    /**
     * The table <code>INFORMATION_SCHEMA.SETTINGS</code>.
     */
    public static final Settings SETTINGS = jdblender.jooq.db.information_schema.tables.Settings.SETTINGS;

    /**
     * The table <code>INFORMATION_SCHEMA.CATALOGS</code>.
     */
    public static final Catalogs CATALOGS = jdblender.jooq.db.information_schema.tables.Catalogs.CATALOGS;

    /**
     * The table <code>INFORMATION_SCHEMA.TYPE_INFO</code>.
     */
    public static final TypeInfo TYPE_INFO = jdblender.jooq.db.information_schema.tables.TypeInfo.TYPE_INFO;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLE_TYPES</code>.
     */
    public static final TableTypes TABLE_TYPES = jdblender.jooq.db.information_schema.tables.TableTypes.TABLE_TYPES;

    /**
     * The table <code>INFORMATION_SCHEMA.INDEXES</code>.
     */
    public static final Indexes INDEXES = jdblender.jooq.db.information_schema.tables.Indexes.INDEXES;

    /**
     * The table <code>INFORMATION_SCHEMA.COLUMNS</code>.
     */
    public static final Columns COLUMNS = jdblender.jooq.db.information_schema.tables.Columns.COLUMNS;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLES</code>.
     */
    public static final jdblender.jooq.db.information_schema.tables.Tables TABLES = jdblender.jooq.db.information_schema.tables.Tables.TABLES;
}
