/**
 * This class is generated by jOOQ
 */
package jdblender.jooq.db.public_;


import javax.annotation.Generated;

import jdblender.jooq.db.public_.tables.Brands;
import jdblender.jooq.db.public_.tables.Models;
import jdblender.jooq.db.public_.tables.Series;
import jdblender.jooq.db.public_.tables.SpareToModel;
import jdblender.jooq.db.public_.tables.Spares;
import jdblender.jooq.db.public_.tables.records.BrandsRecord;
import jdblender.jooq.db.public_.tables.records.ModelsRecord;
import jdblender.jooq.db.public_.tables.records.SeriesRecord;
import jdblender.jooq.db.public_.tables.records.SpareToModelRecord;
import jdblender.jooq.db.public_.tables.records.SparesRecord;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BrandsRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<SeriesRecord> CONSTRAINT_9 = UniqueKeys0.CONSTRAINT_9;
    public static final UniqueKey<ModelsRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<SparesRecord> CONSTRAINT_92 = UniqueKeys0.CONSTRAINT_92;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SeriesRecord, BrandsRecord> CONSTRAINT_91 = ForeignKeys0.CONSTRAINT_91;
    public static final ForeignKey<ModelsRecord, SeriesRecord> CONSTRAINT_87 = ForeignKeys0.CONSTRAINT_87;
    public static final ForeignKey<SparesRecord, BrandsRecord> CONSTRAINT_922 = ForeignKeys0.CONSTRAINT_922;
    public static final ForeignKey<SpareToModelRecord, SparesRecord> CONSTRAINT_5 = ForeignKeys0.CONSTRAINT_5;
    public static final ForeignKey<SpareToModelRecord, ModelsRecord> CONSTRAINT_55 = ForeignKeys0.CONSTRAINT_55;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<BrandsRecord> CONSTRAINT_7 = createUniqueKey(Brands.BRANDS, "CONSTRAINT_7", Brands.BRANDS.ID);
        public static final UniqueKey<SeriesRecord> CONSTRAINT_9 = createUniqueKey(Series.SERIES, "CONSTRAINT_9", Series.SERIES.ID);
        public static final UniqueKey<ModelsRecord> CONSTRAINT_8 = createUniqueKey(Models.MODELS, "CONSTRAINT_8", Models.MODELS.ID);
        public static final UniqueKey<SparesRecord> CONSTRAINT_92 = createUniqueKey(Spares.SPARES, "CONSTRAINT_92", Spares.SPARES.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<SeriesRecord, BrandsRecord> CONSTRAINT_91 = createForeignKey(jdblender.jooq.db.public_.Keys.CONSTRAINT_7, Series.SERIES, "CONSTRAINT_91", Series.SERIES.BRAND_ID);
        public static final ForeignKey<ModelsRecord, SeriesRecord> CONSTRAINT_87 = createForeignKey(jdblender.jooq.db.public_.Keys.CONSTRAINT_9, Models.MODELS, "CONSTRAINT_87", Models.MODELS.SERIES_ID);
        public static final ForeignKey<SparesRecord, BrandsRecord> CONSTRAINT_922 = createForeignKey(jdblender.jooq.db.public_.Keys.CONSTRAINT_7, Spares.SPARES, "CONSTRAINT_922", Spares.SPARES.BRAND_ID);
        public static final ForeignKey<SpareToModelRecord, SparesRecord> CONSTRAINT_5 = createForeignKey(jdblender.jooq.db.public_.Keys.CONSTRAINT_92, SpareToModel.SPARE_TO_MODEL, "CONSTRAINT_5", SpareToModel.SPARE_TO_MODEL.SPARE_ID);
        public static final ForeignKey<SpareToModelRecord, ModelsRecord> CONSTRAINT_55 = createForeignKey(jdblender.jooq.db.public_.Keys.CONSTRAINT_8, SpareToModel.SPARE_TO_MODEL, "CONSTRAINT_55", SpareToModel.SPARE_TO_MODEL.MODEL_ID);
    }
}
