/**
 * This class is generated by jOOQ
 */
package jdblender.jooq.db.public_;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jdblender.jooq.db.DefaultCatalog;
import jdblender.jooq.db.public_.tables.Brands;
import jdblender.jooq.db.public_.tables.Models;
import jdblender.jooq.db.public_.tables.Series;
import jdblender.jooq.db.public_.tables.SpareToModel;
import jdblender.jooq.db.public_.tables.Spares;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -214133980;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.BRANDS</code>.
     */
    public final Brands BRANDS = jdblender.jooq.db.public_.tables.Brands.BRANDS;

    /**
     * The table <code>PUBLIC.SERIES</code>.
     */
    public final Series SERIES = jdblender.jooq.db.public_.tables.Series.SERIES;

    /**
     * The table <code>PUBLIC.MODELS</code>.
     */
    public final Models MODELS = jdblender.jooq.db.public_.tables.Models.MODELS;

    /**
     * The table <code>PUBLIC.SPARES</code>.
     */
    public final Spares SPARES = jdblender.jooq.db.public_.tables.Spares.SPARES;

    /**
     * The table <code>PUBLIC.SPARE_TO_MODEL</code>.
     */
    public final SpareToModel SPARE_TO_MODEL = jdblender.jooq.db.public_.tables.SpareToModel.SPARE_TO_MODEL;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Brands.BRANDS,
            Series.SERIES,
            Models.MODELS,
            Spares.SPARES,
            SpareToModel.SPARE_TO_MODEL);
    }
}
